inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.2

AbcSize:
  Enabled: false

AccessorMethodName:
  Enabled: false

AlignHash:
  Enabled: false

AlignParameters:
  Enabled: false

AssignmentInCondition:
  Enabled: false

CaseIndentation:
  Enabled: false

ClassAndModuleChildren:
  Enabled: false

ClosingParenthesisIndentation:
  Enabled: false

CollectionMethods:
  PreferredMethods:
    inject: 'inject'
    detect: 'detect'

CyclomaticComplexity:
  Enabled: false

Documentation:
  Enabled: false

DoubleNegation:
  Enabled: false

EmptyLineBetweenDefs:
  Enabled: false

EndAlignment:
  Enabled: false

FormatString:
  Enabled: false

GuardClause:
  Enabled: false

HasAndBelongsToMany:
  Enabled: false

IfUnlessModifier:
  Enabled: false

IndentationWidth:
  Enabled: false

Lambda:
  Enabled: false

LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*'

Lint/HandleExceptions:
  Exclude:
    - 'Rakefile'

Metrics/ClassLength:
  Max: 160

Metrics/MethodLength:
  Max: 20

Metrics/ModuleLength:
  Max: 160

Metrics/ParameterLists:
  Max: 6

Metrics/PerceivedComplexity:
  Max: 10

MultilineBlockChain:
  Enabled: false

Next:
  Enabled: false

NumericLiterals:
  Enabled: false

RescueModifier:
  Enabled: false

ShadowingOuterLocalVariable:
  Enabled: false

SignalException:
  EnforcedStyle: only_raise

SingleLineBlockParams:
  Enabled: false

SpaceBeforeFirstArg:
  Enabled: false

SpaceAroundOperators:
  Enabled: false

SpaceInsideBrackets:
  Enabled: false

SpaceInsideParens:
  Enabled: false

SpaceInsideRangeLiteral:
  Enabled: false

StringLiterals:
  Enabled: false

TrivialAccessors:
  ExactNameMatch: true

UnusedBlockArgument:
  Enabled: false

UnusedMethodArgument:
  Enabled: false

WordArray:
  Enabled: false
